apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base                       # shared base (deployments, services, statefulsets)
  - secret-provider-class.yaml       # prod: app secrets
  - ghcr-secret-provider-class.yaml  # prod: GHCR pull secret
  - minio-secret-provider-class.yaml # prod: minio root credentials
